import React from "react"
import { IconMousePointer } from "../../ui/icons/IconMousePointer"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconMousePointer,
  "https://figma.com/design/mVqpnxTTUZW8xwC7vzGYtm?node-id=4039%3A12301",
  {
    props: {},
    example: (props) => <IconMousePointer />,
  },
)
