import React from "react"
import { IconCreditCard } from "../../ui/icons/IconCreditCard"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  IconCreditCard,
  "https://figma.com/design/mVqpnxTTUZW8xwC7vzGYtm?node-id=4039%3A12408",
  {
    props: {},
    example: (props) => <IconCreditCard />,
  },
)
